package model.entity;
// Generated Feb 10, 2017 1:30:33 AM by Hibernate Tools 4.3.1



/**
 * Buku generated by hbm2java
 */
public class Buku  implements java.io.Serializable {


     private long id;
     private String judul;
     private String penerbit;

    public Buku() {
    }

	
    public Buku(long id) {
        this.id = id;
    }
    public Buku(long id, String judul, String penerbit) {
       this.id = id;
       this.judul = judul;
       this.penerbit = penerbit;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getPenerbit() {
        return this.penerbit;
    }
    
    public void setPenerbit(String penerbit) {
        this.penerbit = penerbit;
    }




}


